version: '3'

services:
  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns

  prefect:
    build:
      context: ./prefect
      args:
        API_KEY: pnu_42Hv56FdfkAcquozdSjoAdbtohJLvl1KUmqR
    ports:
      - "4200:4200"

  train:
    build: ./train
    volumes:
      - ./data:/app/data
      - ./mlflow/mlruns:/mlflow/mlruns
    depends_on:
      - mlflow
      - prefect
      
  api:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./mlflow/mlruns:/mlflow/mlruns
    depends_on:
      - mlflow

  anime_application:
    build: ./anime_application
    ports:
      - "3000:3000"
    depends_on:
      - api

  quality_checks:
    build: ./quality_checks
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data

volumes:
  data:
  mlruns: